# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import remote_env_pb2 as remote__env__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class RemoteEnvStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.GetSpaces = channel.unary_unary(
            '/RemoteEnv/GetSpaces',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=remote__env__pb2.Spaces.FromString,
        )
        self.Reset = channel.unary_unary(
            '/RemoteEnv/Reset',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=remote__env__pb2.Observation.FromString,
        )
        self.Step = channel.unary_unary(
            '/RemoteEnv/Step',
            request_serializer=remote__env__pb2.Action.SerializeToString,
            response_deserializer=remote__env__pb2.ObservationRewardDone.FromString,
        )
        self.Render = channel.unary_unary(
            '/RemoteEnv/Render',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=remote__env__pb2.Image.FromString,
        )
        self.Shutdown = channel.unary_unary(
            '/RemoteEnv/Shutdown',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class RemoteEnvServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def GetSpaces(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Render(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteEnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetSpaces': grpc.unary_unary_rpc_method_handler(
            servicer.GetSpaces,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=remote__env__pb2.Spaces.SerializeToString,
        ),
        'Reset': grpc.unary_unary_rpc_method_handler(
            servicer.Reset,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=remote__env__pb2.Observation.SerializeToString,
        ),
        'Step': grpc.unary_unary_rpc_method_handler(
            servicer.Step,
            request_deserializer=remote__env__pb2.Action.FromString,
            response_serializer=remote__env__pb2.ObservationRewardDone.SerializeToString,
        ),
        'Render': grpc.unary_unary_rpc_method_handler(
            servicer.Render,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=remote__env__pb2.Image.SerializeToString,
        ),
        'Shutdown': grpc.unary_unary_rpc_method_handler(
            servicer.Shutdown,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'RemoteEnv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
